from pymongo import MongoClient
from app.core.config import settings

client = MongoClient(settings.MONGO_URI)
db=client[settings.MONGO_DB]
patient_collection = db[settings.MONGO_PATIENT_COLLECTION]
practitioner_collection = db[settings.MONGO_PRACTITIONER_COLLECTION]
organization_collection = db[settings.MONGO_ORGANIZATION_COLLECTION]
locations_collection = db[settings.MONGO_LOCATIONS_COLLECTION]
appointment_collection = db[settings.MONGO_APPOINTMENT_COLLECTION]
conditions_collection = db[settings.MONGO_CONDITIONS_COLLECTION]
coverage_collection = db[settings.MONGO_COVERAGE_COLLECTION]
documentReference_collection = db[settings.MONGO_DOCUMENTREFERENCE_COLLECTION]
encounters_collection = db[settings.MONGO_ENCOUNTERS_COLLECTION]
observations_collection = db[settings.MONGO_OBSERVATIONS_COLLECTION]
medication_requests_collection = db[settings.MONGO_MEDICATION_REQUESTS_COLLECTION]
endpoints_collection = db[settings.MONGO_ENDPOINTS_COLLECTION]
episodeofcare_collection = db[settings.MONGO_EPISODEOFCARE_COLLECTION]
diagnostic_reports_collection = db[settings.MONGO_DIAGNOSTIC_REPORTS_COLLECTION]
immunization_collection = db[settings.MONGO_IMMUNIZATION_COLLECTION]
specimens_collection = db[settings.MONGO_SPECIMENS_COLLECTION]
medications_collection = db[settings.MONGO_MEDICATIONS_COLLECTION]
insurance_collection = db[settings.MONGO_INSURANCE_COLLECTION]
careteams_collection = db[settings.MONGO_CARETEAMS_COLLECTION]
healthcare_services_collection = db[settings.MONGO_HEALTHCARE_SERVICES_COLLECTION]
goals_collection = db[settings.MONGO_GOALS_COLLECTION]
careplans_collection = db[settings.MONGO_CAREPLANS_COLLECTION]
allergies_collection = db[settings.MONGO_ALLERGY_INTOLERANCES_COLLECTION]
devices_collection = db[settings.MONGO_DEVICES_COLLECTION]
procedure_collection = db[settings.MONGO_PROCEDURE_COLLECTION]
relatedperson_collection = db[settings.MONGO_RELATED_PERSON_COLLECTION]